import type { NovaToolDefinition } from "./protocol";

const object = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", properties, ...(required.length ? { required } : {}), additionalProperties: false });
const path = { type: "string", description: "Workspace-relative path. Absolute paths and parent traversal are rejected." };

export const NOVA_TOOLS: NovaToolDefinition[] = [
  { type: "function", function: { name: "fs_checkpoint", description: "Snapshot visible project files before a substantial change. Stored in .nova-work/checkpoints. Hidden and generated files are excluded. Fails explicitly if project exceeds scan or size limits.", parameters: object({}) }, nova: { effect: "write", risk: "low", scope: "filesystem", label: "Creating a project checkpoint…" } },
  { type: "function", function: { name: "task_plan", description: "Publish a short ordered plan before beginning substantial work. Update this plan when the goal changes.", parameters: object({ steps: { type: "array", minItems: 1, maxItems: 12, items: { type: "string" } } }, ["steps"]) }, nova: { effect: "read", risk: "low", scope: "filesystem", label: "Preparing the task plan…" } },
  { type: "function", function: { name: "fs_list", description: "List the current project tree with metadata.", parameters: object({}) }, nova: { effect: "read", risk: "low", scope: "filesystem", label: "Reviewing project files…" } },
  { type: "function", function: { name: "fs_read", description: "Read a UTF-8 text or source file inside the project.", parameters: object({ path }, ["path"]) }, nova: { effect: "read", risk: "low", scope: "filesystem", label: "Reading a project file…" } },
  { type: "function", function: { name: "fs_read_range", description: "Read a line range from a text file without loading the whole file.", parameters: object({ path, start_line: { type: "integer", minimum: 1 }, end_line: { type: "integer", minimum: 1 } }, ["path", "start_line", "end_line"]) }, nova: { effect: "read", risk: "low", scope: "filesystem", label: "Reading part of a project file…" } },
  { type: "function", function: { name: "fs_search", description: "Search project file names and text content.", parameters: object({ query: { type: "string" } }, ["query"]) }, nova: { effect: "read", risk: "low", scope: "filesystem", label: "Searching the project…" } },
  { type: "function", function: { name: "fs_write", description: "Create or replace a text/source file. Nova snapshots existing content for undo.", parameters: object({ path, content: { type: "string" } }, ["path", "content"]) }, nova: { effect: "write", risk: "medium", scope: "filesystem", label: "Updating a project file…" } },
  { type: "function", function: { name: "fs_apply_patch", description: "Replace one exact text block in a file and snapshot the previous version.", parameters: object({ path, old_text: { type: "string" }, new_text: { type: "string" } }, ["path", "old_text", "new_text"]) }, nova: { effect: "write", risk: "medium", scope: "filesystem", label: "Applying a focused patch…" } },
  { type: "function", function: { name: "fs_mkdir", description: "Create a directory inside the project.", parameters: object({ path }, ["path"]) }, nova: { effect: "write", risk: "medium", scope: "filesystem", label: "Creating a project folder…" } },
  { type: "function", function: { name: "fs_move", description: "Move or rename a project file or directory.", parameters: object({ from: path, to: path }, ["from", "to"]) }, nova: { effect: "write", risk: "medium", scope: "filesystem", label: "Moving a project item…" } },
  { type: "function", function: { name: "fs_copy", description: "Copy a project file or directory.", parameters: object({ from: path, to: path }, ["from", "to"]) }, nova: { effect: "write", risk: "medium", scope: "filesystem", label: "Copying a project item…" } },
  { type: "function", function: { name: "fs_delete", description: "Move a project item into Nova's recoverable task trash. Never permanently deletes.", parameters: object({ path }, ["path"]) }, nova: { effect: "write", risk: "high", scope: "filesystem", label: "Moving a project item to recoverable trash…" } },
  { type: "function", function: { name: "fs_undo", description: "Undo the latest file change made by Nova in this project.", parameters: object({}) }, nova: { effect: "write", risk: "medium", scope: "filesystem", label: "Undoing the latest project change…" } },
  { type: "function", function: { name: "shell_exec", description: "Run a non-interactive terminal or PowerShell command from the project directory. Use it for dependency installation, builds, tests, developer tools, and system inspection. Destructive commands remain rejected.", parameters: object({ command: { type: "string" }, purpose: { type: "string" } }, ["command", "purpose"]) }, nova: { effect: "write", risk: "high", scope: "terminal", label: "Running a system command…" } },
  { type: "function", function: { name: "system_install", description: "Install a requested developer application or command-line package using the native package manager (winget on Windows, Homebrew on macOS). Use this instead of telling the user to install npm, Node.js, Git, Python, VS Code, Docker, Ollama, or another package manually.", parameters: object({ package: { type: "string", description: "Package name or package-manager identifier" }, purpose: { type: "string" } }, ["package", "purpose"]) }, nova: { effect: "external", risk: "high", scope: "terminal", label: "Installing a system package…" } },
  { type: "function", function: { name: "preview_start", description: "Start Nova's built-in static web server for an HTML file or folder inside the Work project and open its exact local URL in Nova Workspace Browser. This requires no npm, Node.js, Python, serve, or package installation.", parameters: object({ path, port: { type: "integer", minimum: 1024, maximum: 65535, description: "Optional preferred local port. Omit to choose a free port automatically." } }, ["path"]) }, nova: { effect: "external", risk: "medium", scope: "browser", label: "Starting the local preview…" } },
  { type: "function", function: { name: "web_search", description: "Open a search in the isolated Nova Workspace Browser.", parameters: object({ query: { type: "string" } }, ["query"]) }, nova: { effect: "external", risk: "medium", scope: "browser", label: "Searching the web…" } },
  { type: "function", function: { name: "browser_open", description: "Open an HTTP or HTTPS URL inside Nova Workspace Browser.", parameters: object({ url: { type: "string" } }, ["url"]) }, nova: { effect: "external", risk: "medium", scope: "browser", label: "Opening a website…" } },
  { type: "function", function: { name: "computer_snapshot", description: "Capture the visible primary display for a vision-capable agent.", parameters: object({}) }, nova: { effect: "read", risk: "medium", scope: "computer", label: "Inspecting the screen…" } },
  { type: "function", function: { name: "computer_open_app", description: "Open a non-browser desktop application by visible name.", parameters: object({ name: { type: "string" } }, ["name"]) }, nova: { effect: "external", risk: "high", scope: "computer", label: "Opening an application…" } },
  { type: "function", function: { name: "computer_click", description: "Click the visible display using normalized 0–1000 coordinates.", parameters: object({ x: { type: "integer", minimum: 0, maximum: 1000 }, y: { type: "integer", minimum: 0, maximum: 1000 }, button: { type: "string", enum: ["left", "right", "middle"] }, count: { type: "integer", enum: [1, 2] } }, ["x", "y"]) }, nova: { effect: "external", risk: "high", scope: "computer", label: "Interacting with the screen…" } },
  { type: "function", function: { name: "computer_type", description: "Type non-secret text into the focused field.", parameters: object({ text: { type: "string" } }, ["text"]) }, nova: { effect: "external", risk: "high", scope: "computer", label: "Typing into the active application…" } },
  { type: "function", function: { name: "computer_key", description: "Press a supported key with optional modifiers.", parameters: object({ key: { type: "string" }, modifiers: { type: "array", items: { type: "string", enum: ["shift", "control", "alt", "meta"] } } }, ["key"]) }, nova: { effect: "external", risk: "high", scope: "computer", label: "Using the keyboard…" } },
  { type: "function", function: { name: "computer_scroll", description: "Scroll the focused visible surface.", parameters: object({ amount: { type: "integer", minimum: -20, maximum: 20 } }, ["amount"]) }, nova: { effect: "external", risk: "medium", scope: "computer", label: "Scrolling…" } },
  { type: "function", function: { name: "ask_user", description: "Pause and ask for a missing choice or one-time code. Never request durable secrets.", parameters: object({ prompt: { type: "string" }, placeholder: { type: "string" } }, ["prompt"]) }, nova: { effect: "read", risk: "low", scope: "user-input", label: "Waiting for your input…" } },
];

export const toolDefinition = (name: string) => NOVA_TOOLS.find((tool) => tool.function.name === name);
export const providerTools = NOVA_TOOLS.map(({ nova: _nova, ...tool }) => tool);
