import { ChangeEvent, KeyboardEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Archive, ArrowUp, Bot, Check, ChevronDown, CircleUserRound, Code2, Copy, FileText, Globe2, Image as ImageIcon, Menu, MessageSquare, Mic, Moon, PanelLeftClose, Paperclip, Pencil, Plus, RefreshCw, Search, Settings, Sparkles, Sun, Trash2, X } from 'lucide-react';
import { discoverModels, streamCompletion } from './lib/ai';
import { loadConfig, loadValue, saveChats, saveConfig } from './lib/storage';
import { Chat, Config, Attachment, Message, Provider, getActiveProvider } from './types';

const starterChats: Chat[] = [{ id: 1, title: 'Welcome to Nova', time: 'Today', messages: [] }];

export default function App() {
  const [dark, setDark] = useState(() => loadValue('idk-nova-dark', false));
  const [sidebar, setSidebar] = useState(true);
  const [active, setActive] = useState(() => loadValue('idk-nova-active', 1));
  const [chats, setChats] = useState<Chat[]>(() => loadValue('idk-nova-history', starterChats));
  const [text, setText] = useState(''); const [files, setFiles] = useState<Attachment[]>([]); const [busy, setBusy] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [modelOpen, setModelOpen] = useState(false);
  const [query, setQuery] = useState(''); const [toast, setToast] = useState(''); const [listening, setListening] = useState(false);
  const [config, setConfig] = useState<Config>(loadConfig);
  const [draftConfig, setDraftConfig] = useState<Config>(config); const [syncingId, setSyncingId] = useState(''); const [manualModel, setManualModel] = useState('');
  const fileRef = useRef<HTMLInputElement>(null), endRef = useRef<HTMLDivElement>(null);
  const chat = chats.find(item => item.id === active) || chats[0];
  const activeProvider = getActiveProvider(config);
  const activeDraftProvider = getActiveProvider(draftConfig);
  const visibleChats = useMemo(() => chats.filter(item => !item.archived && item.title.toLowerCase().includes(query.toLowerCase())), [chats, query]);

  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('idk-nova-dark', JSON.stringify(dark)); }, [dark]);
  useEffect(() => { saveChats(chats); }, [chats]);
  useEffect(() => { localStorage.setItem('idk-nova-active', JSON.stringify(active)); }, [active]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [chat?.messages, busy]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 2200); return () => clearTimeout(timer); }, [toast]);

  const upload = (event: ChangeEvent<HTMLInputElement>) => { const selected = [...(event.target.files || [])].slice(0, 5).map(file => ({ name: file.name, type: file.type, url: URL.createObjectURL(file) })); setFiles(current => [...current, ...selected].slice(0, 5)); event.target.value = ''; };
  const fresh = () => { const id = Date.now(); setChats(current => [{ id, title: 'New conversation', time: 'Today', messages: [] }, ...current]); setActive(id); setText(''); };
  const removeChat = (id: number) => { const next = chats.filter(item => item.id !== id); setChats(next.length ? next : starterChats); if (active === id) setActive(next[0]?.id || 1); setToast('Conversation deleted'); };
  const renameChat = (id: number) => { const current = chats.find(item => item.id === id); const title = window.prompt('Rename conversation', current?.title); if (title?.trim()) setChats(items => items.map(item => item.id === id ? { ...item, title: title.trim() } : item)); };
  const archiveChat = (id: number) => { setChats(items => items.map(item => item.id === id ? { ...item, archived: true } : item)); fresh(); setToast('Conversation archived'); };
  const share = async () => { const transcript = chat.messages.map(message => `${message.role === 'user' ? 'You' : 'Nova'}: ${message.content}`).join('\n\n'); try { if (navigator.share) await navigator.share({ title: chat.title, text: transcript }); else { await navigator.clipboard.writeText(transcript); setToast('Conversation copied'); } } catch { /* cancelled */ } };
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); setToast('Copied to clipboard'); };
  const toggleVoice = () => { const Recognition = (window as typeof window & { webkitSpeechRecognition?: new () => any }).webkitSpeechRecognition; if (!Recognition) { setToast('Voice input is not supported in this browser'); return; } const recognition = new Recognition(); recognition.continuous = false; recognition.interimResults = true; recognition.onstart = () => setListening(true); recognition.onend = () => setListening(false); recognition.onresult = (event: any) => setText(Array.from(event.results).map((result: any) => result[0].transcript).join('')); recognition.start(); };
  const send = async () => { if ((!text.trim() && !files.length) || busy || !chat) return; const user: Message = { role: 'user', content: text.trim(), attachments: files }; const title = chat.messages.length ? chat.title : (text.trim() || 'Image conversation').slice(0, 36); setChats(items => items.map(item => item.id === active ? { ...item, title, messages: [...item.messages, user, { role: 'assistant', content: '' }] } : item)); setText(''); setFiles([]); setBusy(true); try { await streamCompletion(config, [...chat.messages, user], token => setChats(items => items.map(item => item.id === active ? { ...item, messages: item.messages.map((message, index) => index === item.messages.length - 1 ? { ...message, content: message.content + token } : message) } : item))); } catch (error) { setChats(items => items.map(item => item.id === active ? { ...item, messages: item.messages.map((message, index) => index === item.messages.length - 1 ? { ...message, content: `I couldn’t connect to ${config.activeModel || 'the selected model'}. Check Settings and make sure the provider is running.\n\n${error instanceof Error ? error.message : 'Unknown error'}` } : message) } : item)); } finally { setBusy(false); } };
  const key = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send(); } };
  const openSettings = () => { setDraftConfig(config); setSettingsOpen(true); setModelOpen(false); };
  const updateDraftProvider = (changes: Partial<Provider>) => setDraftConfig(current => ({ ...current, providers: current.providers.map(provider => provider.id === current.activeProviderId ? { ...provider, ...changes } : provider) }));
  const addProvider = () => { const id = `provider-${Date.now()}`; const provider: Provider = { id, name: 'New provider', baseUrl: '', apiKey: '', models: [] }; setDraftConfig(current => ({ ...current, providers: [...current.providers, provider], activeProviderId: id, activeModel: '' })); };
  const removeProvider = (id: string) => setDraftConfig(current => { const providers = current.providers.filter(provider => provider.id !== id); const next = providers[0]; return { ...current, providers, activeProviderId: next?.id || '', activeModel: next?.models[0] || '' }; });
  const refreshModels = async () => { if (!activeDraftProvider?.baseUrl) return; setSyncingId(activeDraftProvider.id); try { const models = await discoverModels(activeDraftProvider); updateDraftProvider({ models }); setDraftConfig(current => ({ ...current, activeModel: models.includes(current.activeModel) ? current.activeModel : (models[0] || '') })); setToast(models.length ? `${models.length} real model${models.length === 1 ? '' : 's'} found` : 'Provider returned no models'); } catch (error) { setToast(error instanceof Error ? error.message : 'Could not load models'); } finally { setSyncingId(''); } };
  const addManualModel = () => { const model = manualModel.trim(); if (!model || !activeDraftProvider) return; updateDraftProvider({ models: [...new Set([...activeDraftProvider.models, model])] }); setDraftConfig(current => ({ ...current, activeModel: model })); setManualModel(''); };
  const saveSettings = () => { if (!draftConfig.providers.length) { setToast('Add at least one provider'); return; } if (!draftConfig.activeModel) { setToast('Add or discover a model first'); return; } setConfig(draftConfig); saveConfig(draftConfig); setSettingsOpen(false); setToast('Providers and models saved'); };
  if (!chat) return null;

  return <div className="shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <aside className={sidebar ? 'sidebar glass' : 'sidebar hidden'}><div className="side-top"><div className="logo"><div><Sparkles size={17}/></div><b>IDK</b><span>CHAT</span></div><button aria-label="Close sidebar" className="ghost" onClick={() => setSidebar(false)}><PanelLeftClose size={19}/></button></div>
      <button className="new-chat" onClick={fresh}><Pencil size={16}/> New chat <span>⌘ K</span></button><button className="search" onClick={() => setSearchOpen(!searchOpen)}><Search size={16}/> Search chats</button>
      {searchOpen && <div className="search-box"><Search size={14}/><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Search conversations…"/><button onClick={() => { setQuery(''); setSearchOpen(false); }}><X size={13}/></button></div>}
      <div className="history">{['Today', 'Yesterday', 'Previous 7 days'].map(group => <section key={group}><h5>{group}</h5>{visibleChats.filter(item => item.time === group).map(item => <div className={`chat-row ${active === item.id ? 'active' : ''}`} key={item.id}><button className="chat-select" onClick={() => setActive(item.id)}><MessageSquare size={14}/><span>{item.title}</span></button><div className="row-actions"><button title="Rename" onClick={() => renameChat(item.id)}><Pencil/></button><button title="Delete" onClick={() => removeChat(item.id)}><Trash2/></button></div></div>)}</section>)}</div>
      <div className="side-bottom"><button onClick={openSettings}><CircleUserRound size={19}/><span><b>Personal workspace</b><small>Private · Local-first</small></span><Settings size={15}/></button></div></aside>
    <main><header className="glass"><div>{!sidebar && <button aria-label="Open sidebar" className="ghost" onClick={() => setSidebar(true)}><Menu size={20}/></button>}<div className="model-wrap"><button className="model" onClick={() => setModelOpen(!modelOpen)}><span className="model-logo"><Sparkles size={14}/></span><span><b>{activeProvider?.name || 'No provider'}</b><small>{config.activeModel || 'No model selected'}</small></span><ChevronDown size={14}/></button>{modelOpen && <div className="model-menu glass">{activeProvider?.models.map(model => <button key={model} onClick={() => { const next = { ...config, activeModel: model }; setConfig(next); saveConfig(next); setModelOpen(false); }}><span>{model}</span>{config.activeModel === model && <Check/>}</button>)}{!activeProvider?.models.length && <div className="empty-models">No models added</div>}<button onClick={openSettings}><Settings/><span>Manage providers & models</span></button></div>}</div></div><div><button className="ghost" onClick={() => setDark(!dark)}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><button className="share" onClick={share}><Globe2 size={15}/> Share</button><button className="ghost" onClick={openSettings}><Settings size={18}/></button></div></header>
      <div className="conversation">{chat.messages.length === 0 ? <div className="welcome"><div className="hero-logo"><Sparkles size={27}/></div><div className="eyebrow">YOUR PERSONAL INTELLIGENCE</div><h1>What can we create today?</h1><p>Think, build, analyze and explore—with your data under your control.</p><div className="suggestions"><button onClick={() => setText('Help me plan a project from scratch')}><Sparkles/><span><b>Plan a project</b><small>Turn an idea into clear steps</small></span><ArrowUp/></button><button onClick={() => setText('Explain this concept simply: ')}><MessageSquare/><span><b>Explain something</b><small>Make a complex topic simple</small></span><ArrowUp/></button><button onClick={() => fileRef.current?.click()}><ImageIcon/><span><b>Analyze an image</b><small>Upload and ask questions</small></span><ArrowUp/></button><button onClick={() => setText('Write a clean TypeScript function that ')}><Code2/><span><b>Write some code</b><small>Build, debug, or improve</small></span><ArrowUp/></button></div></div> : <div className="message-list">{chat.messages.map((message, index) => <article key={index} className={message.role}><div className="speaker">{message.role === 'assistant' ? <Sparkles size={15}/> : <CircleUserRound size={17}/>}</div><div>{message.attachments?.length ? <div className="attachments">{message.attachments.map((attachment, itemIndex) => attachment.type.startsWith('image/') ? <img key={itemIndex} src={attachment.url}/> : <div className="file" key={itemIndex}><FileText/><span>{attachment.name}</span></div>)}</div> : null}<div className="content">{message.content || <span className="typing"><i/><i/><i/></span>}</div>{message.role === 'assistant' && message.content && <div className="message-actions"><button onClick={() => copy(message.content)}><Copy/> Copy</button><button onClick={() => setChats(items => items.map(item => item.id === active ? { ...item, messages: item.messages.map((value, i) => i === index ? { ...value, liked: !value.liked } : value) } : item))} className={message.liked ? 'selected' : ''}><Check/> Helpful</button><button onClick={() => archiveChat(active)}><Archive/> Archive</button></div>}</div></article>)}<div ref={endRef}/></div>}</div>
      <div className="composer-zone">{files.length > 0 && <div className="file-preview">{files.map((file, index) => <div key={index}>{file.type.startsWith('image/') ? <img src={file.url}/> : <FileText/>}<span>{file.name}</span><button onClick={() => setFiles(current => current.filter((_, itemIndex) => itemIndex !== index))}><X/></button></div>)}</div>}<div className="composer glass"><textarea value={text} onChange={e => setText(e.target.value)} onKeyDown={key} placeholder="Message IDK Nova…" rows={1}/><div className="tools"><div><button title="Attach file" onClick={() => fileRef.current?.click()}><Paperclip size={18}/></button><button title="Attach image" onClick={() => fileRef.current?.click()}><ImageIcon size={18}/></button><span>Images, PDFs and text files</span></div><div><button className={listening ? 'listening' : ''} title="Voice input" onClick={toggleVoice}><Mic size={18}/></button><button className="send" disabled={busy || (!text.trim() && !files.length)} onClick={send}><ArrowUp size={18}/></button></div></div><input ref={fileRef} hidden type="file" multiple accept="image/*,.pdf,.txt,.md,.json,.csv" onChange={upload}/></div><p>IDK Nova can make mistakes. Verify important information.</p></div></main>
    {settingsOpen && <div className="backdrop" onMouseDown={() => setSettingsOpen(false)}><div className="modal provider-modal glass" onMouseDown={event => event.stopPropagation()}>
      <div className="modal-head"><div><div className="settings-mark"><Settings/></div><div><h2>Providers & models</h2><p>Only models discovered from your server or added by you appear here.</p></div></div><button className="ghost" onClick={() => setSettingsOpen(false)}><X/></button></div>
      <div className="provider-layout"><aside className="provider-list"><div className="provider-list-title"><span>Connections</span><button title="Add provider" onClick={addProvider}><Plus/></button></div>{draftConfig.providers.map(provider => <button key={provider.id} className={provider.id === draftConfig.activeProviderId ? 'active' : ''} onClick={() => setDraftConfig(current => ({ ...current, activeProviderId: provider.id, activeModel: provider.models.includes(current.activeModel) ? current.activeModel : (provider.models[0] || '') }))}><Bot/><span><b>{provider.name}</b><small>{provider.models.length} model{provider.models.length === 1 ? '' : 's'}</small></span></button>)}</aside>
      <section className="provider-editor">{activeDraftProvider ? <><div className="provider-editor-head"><b>Connection details</b><button className="danger-link" onClick={() => removeProvider(activeDraftProvider.id)}><Trash2/> Remove</button></div><div className="field-grid"><label>Provider name<input value={activeDraftProvider.name} onChange={e => updateDraftProvider({ name: e.target.value })}/></label><label>API base URL<input value={activeDraftProvider.baseUrl} placeholder="http://localhost:11434/v1" onChange={e => updateDraftProvider({ baseUrl: e.target.value })}/></label></div><label>API key<input type="password" placeholder="Leave empty for local providers" value={activeDraftProvider.apiKey} onChange={e => updateDraftProvider({ apiKey: e.target.value })}/></label><div className="models-head"><div><b>Available models</b><small>Synced from the provider's real /models endpoint</small></div><button className="sync-button" disabled={syncingId === activeDraftProvider.id || !activeDraftProvider.baseUrl} onClick={refreshModels}><RefreshCw className={syncingId ? 'spinning' : ''}/> {syncingId ? 'Checking…' : 'Discover models'}</button></div><div className="model-grid">{activeDraftProvider.models.map(model => <button key={model} className={draftConfig.activeModel === model ? 'selected' : ''} onClick={() => setDraftConfig(current => ({ ...current, activeModel: model }))}><span><Bot/><b>{model}</b></span>{draftConfig.activeModel === model && <Check/>}<X className="remove-model" onClick={event => { event.stopPropagation(); updateDraftProvider({ models: activeDraftProvider.models.filter(value => value !== model) }); if (draftConfig.activeModel === model) setDraftConfig(current => ({ ...current, activeModel: '' })); }}/></button>)}</div>{!activeDraftProvider.models.length && <div className="no-models"><Bot/><b>No models yet</b><span>Start the provider, then discover its installed models—or add an exact model ID manually.</span></div>}<div className="manual-model"><input value={manualModel} placeholder="Exact model ID, e.g. qwen2.5:0.5b" onChange={e => setManualModel(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addManualModel(); } }}/><button onClick={addManualModel}><Plus/> Add manually</button></div></> : <div className="no-models"><Bot/><b>No provider configured</b><span>Add your first local or cloud connection.</span><button className="sync-button" onClick={addProvider}><Plus/> Add provider</button></div>}</section></div>
      <div className="settings-footer"><label>Creativity <span className="range-value">{draftConfig.temperature.toFixed(1)}</span><input className="range" type="range" min="0" max="1" step="0.1" value={draftConfig.temperature} onChange={e => setDraftConfig({ ...draftConfig, temperature: Number(e.target.value) })}/></label><div className="privacy"><Bot/><div><b>Your connection, your data</b><p>Local requests stay on your device. Cloud requests go directly to your configured provider.</p></div></div></div><div className="modal-actions"><button onClick={() => setSettingsOpen(false)}>Cancel</button><button className="save" onClick={saveSettings}>Save changes</button></div>
    </div></div>}
    {toast && <div className="toast"><Check/>{toast}</div>}
  </div>;
}
