import { ChangeEvent, CSSProperties, KeyboardEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Archive, ArrowUp, Bot, Check, ChevronDown, CircleUserRound, Code2, Copy, Database, Download, FileText, Globe2, Image as ImageIcon, Info, Menu, MessageSquare, Mic, Moon, PanelLeftClose, Paperclip, Palette, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Sun, Trash2, Upload, X } from 'lucide-react';
import { discoverModels, streamCompletion, testModel } from './lib/ai';
import { loadConfig, loadManagedConfig, loadValue, saveChats, saveConfig } from './lib/storage';
import { Chat, Config, Attachment, Message, Provider, getActiveProvider } from './types';
import { APP_VERSION, UPDATE_MANIFEST, UpdateManifest, isNewerVersion } from './version';

const starterChats: Chat[] = [{ id: 1, title: 'Welcome to Nova', time: 'Today', messages: [] }];

function BrandMark({ config, className = '' }: { config: Config; className?: string }) {
  return <span className={`brand-mark ${className}`} style={{ '--brand-accent': config.branding.accent } as CSSProperties}>{config.branding.logoDataUrl ? <img src={config.branding.logoDataUrl}/> : <img src={`${import.meta.env.BASE_URL}brand/nova-mark-white-256.png`}/>}</span>;
}

export default function App() {
  const [dark, setDark] = useState(() => loadValue('idk-nova-dark', false));
  const [sidebar, setSidebar] = useState(true);
  const [active, setActive] = useState(() => loadValue('idk-nova-active', 1));
  const [chats, setChats] = useState<Chat[]>(() => loadValue('idk-nova-history', starterChats));
  const [text, setText] = useState(''); const [files, setFiles] = useState<Attachment[]>([]); const [busy, setBusy] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [modelOpen, setModelOpen] = useState(false);
  const [query, setQuery] = useState(''); const [toast, setToast] = useState(''); const [listening, setListening] = useState(false);
  const [config, setConfig] = useState<Config>(loadConfig);
  const [draftConfig, setDraftConfig] = useState<Config>(config); const [syncingId, setSyncingId] = useState(''); const [manualModel, setManualModel] = useState('');
  const [settingsTab, setSettingsTab] = useState<'general'|'models'|'data'|'updates'|'about'>('general'); const [testingModel, setTestingModel] = useState(''); const [verifiedModels, setVerifiedModels] = useState<Record<string, number>>({}); const [updateState, setUpdateState] = useState<'idle'|'checking'|'latest'|'available'|'error'>('idle'); const [updateInfo, setUpdateInfo] = useState<UpdateManifest|null>(null);
  const fileRef = useRef<HTMLInputElement>(null), endRef = useRef<HTMLDivElement>(null), configFileRef = useRef<HTMLInputElement>(null), logoFileRef = useRef<HTMLInputElement>(null);
  const chat = chats.find(item => item.id === active) || chats[0];
  const activeProvider = getActiveProvider(config);
  const activeDraftProvider = getActiveProvider(draftConfig);
  const visibleChats = useMemo(() => chats.filter(item => !item.archived && item.title.toLowerCase().includes(query.toLowerCase())), [chats, query]);

  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('idk-nova-dark', JSON.stringify(dark)); }, [dark]);
  useEffect(() => { saveChats(chats); }, [chats]);
  useEffect(() => { localStorage.setItem('idk-nova-active', JSON.stringify(active)); }, [active]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [chat?.messages, busy]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 2200); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { loadManagedConfig().then(managed => { if (!managed) return; setConfig(current => { const next = { ...current, ...managed, branding: { ...current.branding, ...managed.branding }, database: { ...current.database, ...managed.database } } as Config; saveConfig(next); return next; }); }); }, []);

  const upload = (event: ChangeEvent<HTMLInputElement>) => { const selected = [...(event.target.files || [])].slice(0, 5).map(file => ({ name: file.name, type: file.type, url: URL.createObjectURL(file) })); setFiles(current => [...current, ...selected].slice(0, 5)); event.target.value = ''; };
  const fresh = () => { const id = Date.now(); setChats(current => [{ id, title: 'New conversation', time: 'Today', messages: [] }, ...current]); setActive(id); setText(''); };
  const removeChat = (id: number) => { const next = chats.filter(item => item.id !== id); setChats(next.length ? next : starterChats); if (active === id) setActive(next[0]?.id || 1); setToast('Conversation deleted'); };
  const renameChat = (id: number) => { const current = chats.find(item => item.id === id); const title = window.prompt('Rename conversation', current?.title); if (title?.trim()) setChats(items => items.map(item => item.id === id ? { ...item, title: title.trim() } : item)); };
  const archiveChat = (id: number) => { setChats(items => items.map(item => item.id === id ? { ...item, archived: true } : item)); fresh(); setToast('Conversation archived'); };
  const share = async () => { const transcript = chat.messages.map(message => `${message.role === 'user' ? 'You' : 'Nova'}: ${message.content}`).join('\n\n'); try { if (navigator.share) await navigator.share({ title: chat.title, text: transcript }); else { await navigator.clipboard.writeText(transcript); setToast('Conversation copied'); } } catch { /* cancelled */ } };
  const copy = async (value: string) => { await navigator.clipboard.writeText(value); setToast('Copied to clipboard'); };
  const toggleVoice = () => { const Recognition = (window as typeof window & { webkitSpeechRecognition?: new () => any }).webkitSpeechRecognition; if (!Recognition) { setToast('Voice input is not supported in this browser'); return; } const recognition = new Recognition(); recognition.continuous = false; recognition.interimResults = true; recognition.onstart = () => setListening(true); recognition.onend = () => setListening(false); recognition.onresult = (event: any) => setText(Array.from(event.results).map((result: any) => result[0].transcript).join('')); recognition.start(); };
  const send = async () => { if ((!text.trim() && !files.length) || busy || !chat) return; const user: Message = { role: 'user', content: text.trim(), attachments: files }; const title = chat.messages.length ? chat.title : (text.trim() || 'Image conversation').slice(0, 36); setChats(items => items.map(item => item.id === active ? { ...item, title, messages: [...item.messages, user, { role: 'assistant', content: '' }] } : item)); setText(''); setFiles([]); setBusy(true); try { await streamCompletion(config, [...chat.messages, user], token => setChats(items => items.map(item => item.id === active ? { ...item, messages: item.messages.map((message, index) => index === item.messages.length - 1 ? { ...message, content: message.content + token } : message) } : item))); } catch (error) { setChats(items => items.map(item => item.id === active ? { ...item, messages: item.messages.map((message, index) => index === item.messages.length - 1 ? { ...message, content: `I couldn’t connect to ${config.activeModel || 'the selected model'}. Check Settings and make sure the provider is running.\n\n${error instanceof Error ? error.message : 'Unknown error'}` } : message) } : item)); } finally { setBusy(false); } };
  const key = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send(); } };
  const openSettings = () => { setDraftConfig(config); setSettingsOpen(true); setModelOpen(false); };
  const updateDraftProvider = (changes: Partial<Provider>) => setDraftConfig(current => ({ ...current, providers: current.providers.map(provider => provider.id === current.activeProviderId ? { ...provider, ...changes } : provider) }));
  const addProvider = () => { const id = `provider-${Date.now()}`; const provider: Provider = { id, name: 'New provider', baseUrl: '', apiKey: '', models: [] }; setDraftConfig(current => ({ ...current, providers: [...current.providers, provider], activeProviderId: id, activeModel: '' })); };
  const removeProvider = (id: string) => setDraftConfig(current => { const providers = current.providers.filter(provider => provider.id !== id); const next = providers[0]; return { ...current, providers, activeProviderId: next?.id || '', activeModel: next?.models[0] || '' }; });
  const refreshModels = async () => { if (!activeDraftProvider?.baseUrl) return; setSyncingId(activeDraftProvider.id); try { const models = await discoverModels(activeDraftProvider); updateDraftProvider({ models }); setDraftConfig(current => ({ ...current, activeModel: models.includes(current.activeModel) ? current.activeModel : (models[0] || '') })); setToast(models.length ? `${models.length} real model${models.length === 1 ? '' : 's'} found` : 'Provider returned no models'); } catch (error) { setToast(error instanceof Error ? error.message : 'Could not load models'); } finally { setSyncingId(''); } };
  const addManualModel = async () => { const model = manualModel.trim(); if (!model || !activeDraftProvider) return; setTestingModel(model); try { const latency = await testModel(activeDraftProvider, model); updateDraftProvider({ models: [...new Set([...activeDraftProvider.models, model])] }); setDraftConfig(current => ({ ...current, activeModel: model })); setVerifiedModels(current => ({ ...current, [`${activeDraftProvider.id}:${model}`]: latency })); setManualModel(''); setToast(`Model accepted · ${latency} ms`); } catch (error) { setToast(error instanceof Error ? error.message : 'Model rejected'); } finally { setTestingModel(''); } };
  const verifyModel = async (model: string) => { if (!activeDraftProvider) return; setTestingModel(model); try { const latency = await testModel(activeDraftProvider, model); setVerifiedModels(current => ({ ...current, [`${activeDraftProvider.id}:${model}`]: latency })); setToast(`Model verified in ${latency} ms`); } catch (error) { setToast(error instanceof Error ? error.message : 'Model test failed'); } finally { setTestingModel(''); } };
  const checkUpdates = async () => { setUpdateState('checking'); try { const response = await fetch(`${UPDATE_MANIFEST}?t=${Date.now()}`, { cache: 'no-store' }); if (!response.ok) throw new Error(); const manifest: UpdateManifest = await response.json(); setUpdateInfo(manifest); setUpdateState(isNewerVersion(manifest.version, APP_VERSION) ? 'available' : 'latest'); } catch { setUpdateState('error'); } };
  const importConfig = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const value = JSON.parse(String(reader.result)); setDraftConfig(current => ({ ...current, ...value, branding: { ...current.branding, ...value.branding }, database: { ...current.database, ...value.database } })); setToast('Configuration imported'); } catch { setToast('Invalid configuration file'); } }; reader.readAsText(file); event.target.value = ''; };
  const exportConfig = () => { const safe = { ...draftConfig, providers: draftConfig.providers.map(provider => ({ ...provider, apiKey: '' })), database: { ...draftConfig.database, url: '' } }; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(safe, null, 2)], { type: 'application/json' })); link.download = 'idk-nova.config.json'; link.click(); URL.revokeObjectURL(link.href); };
  const uploadLogo = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || file.size > 2_000_000) { setToast('Choose an image under 2 MB'); return; } const reader = new FileReader(); reader.onload = () => setDraftConfig(current => ({ ...current, branding: { ...current.branding, logoDataUrl: String(reader.result) } })); reader.readAsDataURL(file); event.target.value = ''; };
  const saveSettings = () => { if (!draftConfig.providers.length) { setToast('Add at least one provider'); return; } if (!draftConfig.activeModel) { setToast('Add or discover a model first'); return; } setConfig(draftConfig); saveConfig(draftConfig); setSettingsOpen(false); setToast('Providers and models saved'); };
  if (!chat) return null;

  return <div className="shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <aside className={sidebar ? 'sidebar glass' : 'sidebar hidden'}><div className="side-top"><div className="logo"><BrandMark config={config}/><b>{config.branding.appName}</b></div><button aria-label="Close sidebar" className="ghost" onClick={() => setSidebar(false)}><PanelLeftClose size={19}/></button></div>
      <button className="new-chat" onClick={fresh}><Pencil size={16}/> New chat <span>⌘ K</span></button><button className="search" onClick={() => setSearchOpen(!searchOpen)}><Search size={16}/> Search chats</button>
      {searchOpen && <div className="search-box"><Search size={14}/><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Search conversations…"/><button onClick={() => { setQuery(''); setSearchOpen(false); }}><X size={13}/></button></div>}
      <div className="history">{['Today', 'Yesterday', 'Previous 7 days'].map(group => <section key={group}><h5>{group}</h5>{visibleChats.filter(item => item.time === group).map(item => <div className={`chat-row ${active === item.id ? 'active' : ''}`} key={item.id}><button className="chat-select" onClick={() => setActive(item.id)}><MessageSquare size={14}/><span>{item.title}</span></button><div className="row-actions"><button title="Rename" onClick={() => renameChat(item.id)}><Pencil/></button><button title="Delete" onClick={() => removeChat(item.id)}><Trash2/></button></div></div>)}</section>)}</div>
      <div className="side-bottom"><button onClick={openSettings}><CircleUserRound size={19}/><span><b>{config.branding.workspaceName}</b><small>Private · Local-first</small></span><Settings size={15}/></button></div></aside>
    <main><header className="glass"><div>{!sidebar && <button aria-label="Open sidebar" className="ghost" onClick={() => setSidebar(true)}><Menu size={20}/></button>}<div className="model-wrap"><button className="model" onClick={() => setModelOpen(!modelOpen)}><BrandMark config={config} className="model-logo"/><span><b>{activeProvider?.name || 'No provider'}</b><small>{config.activeModel || 'No model selected'}</small></span><ChevronDown size={14}/></button>{modelOpen && <div className="model-menu glass">{activeProvider?.models.map(model => <button key={model} onClick={() => { const next = { ...config, activeModel: model }; setConfig(next); saveConfig(next); setModelOpen(false); }}><span>{model}</span>{config.activeModel === model && <Check/>}</button>)}{!activeProvider?.models.length && <div className="empty-models">No models added</div>}<button onClick={openSettings}><Settings/><span>Manage providers & models</span></button></div>}</div></div><div><button className="ghost" onClick={() => setDark(!dark)}>{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><button className="share" onClick={share}><Globe2 size={15}/> Share</button><button className="ghost" onClick={openSettings}><Settings size={18}/></button></div></header>
      <div className="conversation">{chat.messages.length === 0 ? <div className="welcome"><div className="hero-logo"><Sparkles size={27}/></div><div className="eyebrow">YOUR PERSONAL INTELLIGENCE</div><h1>What can we create today?</h1><p>Think, build, analyze and explore—with your data under your control.</p><div className="suggestions"><button onClick={() => setText('Help me plan a project from scratch')}><Sparkles/><span><b>Plan a project</b><small>Turn an idea into clear steps</small></span><ArrowUp/></button><button onClick={() => setText('Explain this concept simply: ')}><MessageSquare/><span><b>Explain something</b><small>Make a complex topic simple</small></span><ArrowUp/></button><button onClick={() => fileRef.current?.click()}><ImageIcon/><span><b>Analyze an image</b><small>Upload and ask questions</small></span><ArrowUp/></button><button onClick={() => setText('Write a clean TypeScript function that ')}><Code2/><span><b>Write some code</b><small>Build, debug, or improve</small></span><ArrowUp/></button></div></div> : <div className="message-list">{chat.messages.map((message, index) => <article key={index} className={message.role}><div className="speaker">{message.role === 'assistant' ? <Sparkles size={15}/> : <CircleUserRound size={17}/>}</div><div>{message.attachments?.length ? <div className="attachments">{message.attachments.map((attachment, itemIndex) => attachment.type.startsWith('image/') ? <img key={itemIndex} src={attachment.url}/> : <div className="file" key={itemIndex}><FileText/><span>{attachment.name}</span></div>)}</div> : null}<div className="content">{message.content || <span className="typing"><i/><i/><i/></span>}</div>{message.role === 'assistant' && message.content && <div className="message-actions"><button onClick={() => copy(message.content)}><Copy/> Copy</button><button onClick={() => setChats(items => items.map(item => item.id === active ? { ...item, messages: item.messages.map((value, i) => i === index ? { ...value, liked: !value.liked } : value) } : item))} className={message.liked ? 'selected' : ''}><Check/> Helpful</button><button onClick={() => archiveChat(active)}><Archive/> Archive</button></div>}</div></article>)}<div ref={endRef}/></div>}</div>
      <div className="composer-zone">{files.length > 0 && <div className="file-preview">{files.map((file, index) => <div key={index}>{file.type.startsWith('image/') ? <img src={file.url}/> : <FileText/>}<span>{file.name}</span><button onClick={() => setFiles(current => current.filter((_, itemIndex) => itemIndex !== index))}><X/></button></div>)}</div>}<div className="composer glass"><textarea value={text} onChange={e => setText(e.target.value)} onKeyDown={key} placeholder="Message IDK Nova…" rows={1}/><div className="tools"><div><button title="Attach file" onClick={() => fileRef.current?.click()}><Paperclip size={18}/></button><button title="Attach image" onClick={() => fileRef.current?.click()}><ImageIcon size={18}/></button><span>Images, PDFs and text files</span></div><div><button className={listening ? 'listening' : ''} title="Voice input" onClick={toggleVoice}><Mic size={18}/></button><button className="send" disabled={busy || (!text.trim() && !files.length)} onClick={send}><ArrowUp size={18}/></button></div></div><input ref={fileRef} hidden type="file" multiple accept="image/*,.pdf,.txt,.md,.json,.csv" onChange={upload}/></div><p>IDK Nova can make mistakes. Verify important information.</p></div></main>
    {settingsOpen && <div className="backdrop" onMouseDown={() => setSettingsOpen(false)}><div className="settings-window" onMouseDown={event => event.stopPropagation()}>
      <aside className="settings-nav"><div className="settings-title"><BrandMark config={draftConfig}/><span><b>{draftConfig.branding.appName}</b><small>Settings</small></span></div><nav>{([['general',SlidersHorizontal,'General'],['models',Bot,'Models'],['data',Database,'Data & memory'],['updates',Download,'Updates'],['about',Info,'About']] as const).map(([id,Icon,label]) => <button key={id} className={settingsTab === id ? 'active' : ''} onClick={() => setSettingsTab(id)}><Icon/>{label}</button>)}</nav><div className="config-actions"><button onClick={() => configFileRef.current?.click()}><Upload/> Import config</button><button onClick={exportConfig}><Download/> Export config</button><input hidden ref={configFileRef} type="file" accept="application/json,.json" onChange={importConfig}/></div></aside>
      <section className="settings-main"><header><div><h2>{settingsTab === 'general' ? 'General' : settingsTab === 'models' ? 'Models & providers' : settingsTab === 'data' ? 'Data & memory' : settingsTab === 'updates' ? 'Software update' : 'About'}</h2><p>{settingsTab === 'models' ? 'Connect and verify the AI models you actually use.' : settingsTab === 'general' ? 'Make Nova feel at home in your organization.' : 'Configure this part of your workspace.'}</p></div><button className="ghost" onClick={() => setSettingsOpen(false)}><X/></button></header><div className="settings-content">
        {settingsTab === 'general' && <><div className="preference-section"><h3>Identity</h3><p>These values appear throughout the app and can be distributed in a managed config.</p><div className="brand-editor"><BrandMark config={draftConfig} className="brand-preview"/><div><button className="secondary" onClick={() => logoFileRef.current?.click()}>Choose logo</button>{draftConfig.branding.logoDataUrl && <button className="text-button" onClick={() => setDraftConfig(current => ({ ...current, branding: { ...current.branding, logoDataUrl: '' } }))}>Use default</button>}<input hidden ref={logoFileRef} type="file" accept="image/png,image/svg+xml,image/webp" onChange={uploadLogo}/><small>Transparent PNG, SVG or WebP · maximum 2 MB</small></div></div><div className="field-grid"><label>Application name<input value={draftConfig.branding.appName} onChange={e => setDraftConfig(current => ({ ...current, branding: { ...current.branding, appName: e.target.value } }))}/></label><label>Workspace name<input value={draftConfig.branding.workspaceName} onChange={e => setDraftConfig(current => ({ ...current, branding: { ...current.branding, workspaceName: e.target.value } }))}/></label></div><label>Accent color<div className="color-field"><input type="color" value={draftConfig.branding.accent} onChange={e => setDraftConfig(current => ({ ...current, branding: { ...current.branding, accent: e.target.value } }))}/><code>{draftConfig.branding.accent}</code></div></label></div><div className="preference-section"><h3>Response style</h3><label>Creativity <span className="range-value">{draftConfig.temperature.toFixed(1)}</span><input className="range" type="range" min="0" max="1" step="0.1" value={draftConfig.temperature} onChange={e => setDraftConfig({ ...draftConfig, temperature: Number(e.target.value) })}/></label></div></>}
        {settingsTab === 'models' && <div className="models-settings"><div className="connection-tabs">{draftConfig.providers.map(provider => <button key={provider.id} className={provider.id === draftConfig.activeProviderId ? 'active' : ''} onClick={() => setDraftConfig(current => ({ ...current, activeProviderId: provider.id, activeModel: provider.models[0] || '' }))}><span className="status-dot"/>{provider.name}<small>{provider.models.length}</small></button>)}<button className="add-connection" onClick={addProvider}><Plus/> New</button></div>{activeDraftProvider ? <><div className="preference-section"><div className="section-heading"><div><h3>Connection</h3><p>OpenAI-compatible endpoint</p></div><button className="danger-link" onClick={() => removeProvider(activeDraftProvider.id)}><Trash2/> Remove</button></div><div className="field-grid"><label>Name<input value={activeDraftProvider.name} onChange={e => updateDraftProvider({ name: e.target.value })}/></label><label>Base URL<input value={activeDraftProvider.baseUrl} onChange={e => updateDraftProvider({ baseUrl: e.target.value })}/></label></div><label>API key<input type="password" value={activeDraftProvider.apiKey} placeholder="Not required for local providers" onChange={e => updateDraftProvider({ apiKey: e.target.value })}/></label><button className="primary-action" disabled={syncingId === activeDraftProvider.id} onClick={refreshModels}><RefreshCw className={syncingId ? 'spinning' : ''}/> {syncingId ? 'Connecting…' : 'Connect & discover models'}</button></div><div className="preference-section"><div className="section-heading"><div><h3>Models</h3><p>A model is accepted only after the provider responds successfully.</p></div></div><div className="verified-list">{activeDraftProvider.models.map(model => { const latency = verifiedModels[`${activeDraftProvider.id}:${model}`]; return <div key={model} className={draftConfig.activeModel === model ? 'active' : ''}><button className="model-name" onClick={() => setDraftConfig(current => ({ ...current, activeModel: model }))}><span className={latency ? 'verified-dot' : 'status-dot'}/><b>{model}</b>{draftConfig.activeModel === model && <small>Active</small>}</button><span>{latency ? <em><ShieldCheck/> Verified · {latency} ms</em> : <button className="test-button" disabled={testingModel === model} onClick={() => verifyModel(model)}>{testingModel === model ? 'Testing…' : 'Test'}</button>}<button className="icon-button" onClick={() => updateDraftProvider({ models: activeDraftProvider.models.filter(value => value !== model) })}><X/></button></span></div>})}</div><div className="manual-model"><input value={manualModel} placeholder="Exact model ID" onChange={e => setManualModel(e.target.value)}/><button onClick={addManualModel}><Plus/> Add</button></div></div></> : <div className="empty-state">Add a provider to begin.</div>}</div>}
        {settingsTab === 'data' && <><div className="preference-section"><div className="setting-row"><div><h3>Project database</h3><p>Connect a database for long-term memory and organization data.</p></div><button className={`switch ${draftConfig.database.enabled ? 'on' : ''}`} onClick={() => setDraftConfig(current => ({ ...current, database: { ...current.database, enabled: !current.database.enabled, kind: current.database.enabled ? 'none' : 'postgresql' } }))}><i/></button></div>{draftConfig.database.enabled && <><label>Database type<select value={draftConfig.database.kind} onChange={e => setDraftConfig(current => ({ ...current, database: { ...current.database, kind: e.target.value as Config['database']['kind'] } }))}><option value="postgresql">PostgreSQL</option><option value="mysql">MySQL</option><option value="sqlite">SQLite</option><option value="http">HTTP API</option></select></label><label>Connection URL<input type="password" value={draftConfig.database.url} placeholder="postgresql://user:password@host/database" onChange={e => setDraftConfig(current => ({ ...current, database: { ...current.database, url: e.target.value } }))}/></label><div className="setting-row compact"><div><b>Use for AI memory</b><p>Allow selected models to retrieve stored context.</p></div><button className={`switch ${draftConfig.database.useForMemory ? 'on' : ''}`} onClick={() => setDraftConfig(current => ({ ...current, database: { ...current.database, useForMemory: !current.database.useForMemory } }))}><i/></button></div></>}</div><div className="notice"><ShieldCheck/><div><b>Credentials stay local</b><p>Database secrets are excluded when exporting a managed configuration.</p></div></div></>}
        {settingsTab === 'updates' && <div className="update-panel"><div className="update-orb"><Download/></div><h3>{draftConfig.branding.appName} {APP_VERSION}</h3><p>{updateState === 'available' ? `Version ${updateInfo?.version} is ready.` : updateState === 'latest' ? 'You’re running the latest version.' : updateState === 'error' ? 'Could not reach the update server.' : 'Check the official release channel for updates.'}</p>{updateInfo?.notes && updateState === 'available' && <ul>{updateInfo.notes.map(note => <li key={note}>{note}</li>)}</ul>}<button className="primary-action" disabled={updateState === 'checking'} onClick={checkUpdates}><RefreshCw className={updateState === 'checking' ? 'spinning' : ''}/>{updateState === 'checking' ? 'Checking…' : 'Check for updates'}</button>{updateState === 'available' && <a className="download-update" href={updateInfo?.installerUrl} target="_blank">Download version {updateInfo?.version}</a>}<small>Web builds update automatically after each published release.</small></div>}
        {settingsTab === 'about' && <div className="about-panel"><BrandMark config={draftConfig} className="about-logo"/><h3>{draftConfig.branding.appName}</h3><p>Private, configurable AI for individuals and organizations.</p><dl><div><dt>Version</dt><dd>{APP_VERSION}</dd></div><div><dt>Configuration</dt><dd>Managed JSON supported</dd></div><div><dt>License</dt><dd>Open source · MIT</dd></div></dl></div>}
      </div><footer><span>Changes stay on this device unless exported.</span><div><button onClick={() => setSettingsOpen(false)}>Cancel</button><button className="save" onClick={saveSettings}>Save changes</button></div></footer></section>
    </div></div>}
    {toast && <div className="toast"><Check/>{toast}</div>}
  </div>;
}
