export type Attachment = { name: string; type: string; url: string };
export type Message = { role: 'user' | 'assistant'; content: string; attachments?: Attachment[]; liked?: boolean; quote?: string; generating?: boolean; durationMs?: number; generationKind?: 'text' | 'image'; toolExecutions?: { name: string; result: string }[]; usedPacks?: { id: string; name: string; version: string }[]; inputAnswers?: { id: string; question: string; answer: string }[] };
export type ResponseMemory = { providerId: string; model: string; previousResponseId: string };
export type Chat = { id: number; title: string; time: string; messages: Message[]; archived?: boolean; folderId?: string; workspaceId?: string; temporary?: boolean; responseMemory?: ResponseMemory; selectedPacks?: string[] };
export type ChatFolder = { id: string; name: string; color: string; icon: 'folder' | 'work' | 'code' | 'sparkles' | 'book' | 'heart' | 'star' | 'rocket' | 'lab' | 'study' };
export type WorkProject = { id: string; name: string; rootPath: string; createdAt: number; fileCount: number; truncated?: boolean; agentAccess?: 'ask' | 'safe' | 'auto'; localOnly?: boolean; memoryNotes?: { id: string; scope: string; text: string; pinned: boolean }[] };
export type Provider = { id: string; name: string; baseUrl: string; apiKey: string; apiKeyStored?: boolean; credentialAccount?: string; models: string[] };
export type Branding = { appName: string; workspaceName: string; accent: string; logoDataUrl: string };
export type DatabaseConfig = { enabled: boolean; kind: 'none' | 'postgresql' | 'mysql' | 'sqlite' | 'http'; url: string; useForMemory: boolean };
export type ThemePreference = 'system' | 'light' | 'dark';
export type Config = { providers: Provider[]; activeProviderId: string; activeModel: string; temperature: number; theme: ThemePreference; branding: Branding; database: DatabaseConfig };
export const defaultProvider: Provider = { id: 'ollama-local', name: 'Ollama Local', baseUrl: 'http://127.0.0.1:11434/v1', apiKey: '', models: [] };
export const defaultConfig: Config = { providers: [], activeProviderId: '', activeModel: '', temperature: 0.5, theme: 'system', branding: { appName: 'Nova', workspaceName: 'Personal workspace', accent: '#171717', logoDataUrl: '' }, database: { enabled: false, kind: 'none', url: '', useForMemory: false } };
export const getActiveProvider = (config: Config) => config.providers.find(provider => provider.id === config.activeProviderId) || config.providers[0];
